version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./skymarket
      dockerfile: Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./skymarket:/skymarket
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  pg_data: