# Generated by Django 3.2.6 on 2023-10-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20231015_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ('-created_at',), 'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
    ]
